---
title: "russia_spark"
author: "Kei Oyama"
date: "2024-04-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
rm(list = ls("all.names" = TRUE))
```

```{r}
options(repos = c(CRAN = "https://cloud.r-project.org/"))


install.packages("sparklyr")
install.packages("MazamaSpatialUtils")
install.packages("reader")
```

```{r}
library(ggplot2)
library(patchwork)
library(rnaturalearth)
library(MazamaSpatialUtils)
library(sf)
library(sparklyr)
library(arrow)
library(dplyr)
library(stringr)
library(reader)
```


```{r}
conf <- spark_config()
  
#conf$`sparklyr.cores.local` <- 14
  conf$`sparklyr.shell.driver-memory` <- "20G"#自分のパソコン
  conf$spark.memory.fraction <- 0.9

  # Connect to Spark
spark_conn <-spark_connect(master = "local",  config = conf)
```


```{r}
dat_area_segs_daily_WE_2018 <- spark_read_parquet( sc = spark_conn, name = "dat_area_segs_daily_WE_2018",
                                    memory = FALSE,  # memory unload  faster to readl for parquest
           
 "/Users/oyamakei/Library/CloudStorage/GoogleDrive-keio@fisheries.agr.iwate-u.ac.jp/Shared drives/gakuLab_data/Project/GFW_data_integration_2/raw/big_area_segs_daily/big_area_segs_daily_WE_2018.parquet")
 
dat_area_segs_daily_WE_2019 <- spark_read_parquet( sc = spark_conn, name = "dat_area_segs_daily_WE_2019",
                                    memory = FALSE,  # memory unload  faster to readl for parquest
           
 "/Users/oyamakei/Library/CloudStorage/GoogleDrive-keio@fisheries.agr.iwate-u.ac.jp/Shared drives/gakuLab_data/Project/GFW_data_integration_2/raw/big_area_segs_daily/big_area_segs_daily_WE_2019.parquet")

dat_area_segs_daily_WE_2020 <- spark_read_parquet( sc = spark_conn, name = "dat_area_segs_daily_WE_2020",
                                    memory = FALSE,  # memory unload  faster to readl for parquest
           
 "/Users/oyamakei/Library/CloudStorage/GoogleDrive-keio@fisheries.agr.iwate-u.ac.jp/Shared drives/gakuLab_data/Project/GFW_data_integration_2/raw/big_area_segs_daily/big_area_segs_daily_WE_2020.parquet")

dat_area_segs_daily_WE_2021 <- spark_read_parquet( sc = spark_conn, name = "dat_area_segs_daily_WE_2021",
                                    memory = FALSE,  # memory unload  faster to readl for parquest
           
 "/Users/oyamakei/Library/CloudStorage/GoogleDrive-keio@fisheries.agr.iwate-u.ac.jp/Shared drives/gakuLab_data/Project/GFW_data_integration_2/raw/big_area_segs_daily/big_area_segs_daily_WE_2021.parquet")

dat_area_segs_daily_WE_2022 <- spark_read_parquet( sc = spark_conn, name = "dat_area_segs_daily_WE_2022",
                                    memory = FALSE,  # memory unload  faster to readl for parquest
           
 "/Users/oyamakei/Library/CloudStorage/GoogleDrive-keio@fisheries.agr.iwate-u.ac.jp/Shared drives/gakuLab_data/Project/GFW_data_integration_2/raw/big_area_segs_daily/big_area_segs_daily_WE_2022.parquet")

dat_area_segs_daily_WE_2023 <- spark_read_parquet( sc = spark_conn, name = "dat_area_segs_daily_WE_2023",
                                    memory = FALSE,  # memory unload  faster to readl for parquest
           
 "/Users/oyamakei/Library/CloudStorage/GoogleDrive-keio@fisheries.agr.iwate-u.ac.jp/Shared drives/gakuLab_data/Project/GFW_data_integration_2/raw/big_area_segs_daily/big_area_segs_daily_WE_2023.parquet")

eez_info_list <- spark_read_parquet( sc = spark_conn, name = "eez_info_list",
                                    memory = FALSE,  # memory unload  faster to readl for parquest
           
 "/Users/oyamakei/Library/CloudStorage/GoogleDrive-keio@fisheries.agr.iwate-u.ac.jp/Shared drives/gakuLab_data/Original/gfw/eez_info/eez_info_list.parquet")

dat_area_segs_daily_WE_2018_new <- spark_read_parquet( sc = spark_conn, name = "dat_area_segs_daily_WE_2018_new",
                                    memory = FALSE,  # memory unload  faster to readl for parquest
           
 "/Users/oyamakei/Library/CloudStorage/GoogleDrive-keio@fisheries.agr.iwate-u.ac.jp/Shared drives/gakuLab_data/Original/gfw/daily/fixed_upto2023/dat_daily_2017.parquet")

dat_sonota<- spark_read_parquet( sc = spark_conn, name = "dat_sonota",
                                    memory = FALSE,  # memory unload  faster to readl for parquest
           
 "/Users/oyamakei/Library/CloudStorage/GoogleDrive-keio@fisheries.agr.iwate-u.ac.jp/Shared drives/gakuLab_data/Project/GFW_data_integration_2/その他/dat_bq_temp_18_23.parquet")


list_country_codes <- spark_read_csv(path = "~/Google Drive/Shared drives/gakuLab_data/Project/gakuLab_vessel_list/list_country/GFWcountry_codes19Aug23_gakulab.csv",
                                     sc = spark_conn,
                                     memory = FALSE,
                                     name = "list_country", delimiter = ",", header = TRUE)

  #"~GoogleDrive/Shared drives/gakuLab_data/Original/gfw/daily/fixed_upto2023/dat_daily_2020.parquet")

#spark_disconnect(sc = spark_conn)
```




#日本でフィルタリングはできるがロシアをどうするのか
```{r}
dat_sonota <- dat_sonota %>% 
  rename(eez_id = eez_value)

dat_sonota_joined <- dat_sonota %>%
  left_join(eez_info_list, by = "eez_id")


temp_round_0 <- 2  # 小数点第2位
temp_round_1 <- 3  # 小数点第3位
temp_round_2 <- 4  # 小数点第4位


russia_eez_japan_2018 <- dat_area_segs_daily_WE_2018 %>%
  mutate(country_code = as.integer(floor(ssvid/1000000)))  %>%  　　# ssvidから国コード生成
  left_join(list_country_codes, by = c("country_code" = "code" )) %>%
  filter(country_code %in% "273") %>% 
  # dat_sonota_joined を first_timestamp で結合
  left_join(dat_sonota_joined, by = c("first_timestamp", "seg_id")) %>% 
  # territory1 が "Japan" の行のみフィルタ
  filter(eez_id == 8487 & reporting_name == "Japanese Exclusive Economic Zone", ) %>% 
  #select(seg_id, ssvid, first_timestamp, eez_id, reporting_name) %>% 
   mutate(avg_lon = substring_index(avg_lat_lon, " ", 1),#avg_lat_lonをavg_lon,avg_latに分ける
          avg_lat = substring_index(avg_lat_lon, " ", -1),
          seg_id_num  = as.numeric(str_sub(seg_id, start = 1L, end = -1L)))%>%
  mutate(avg_lon =as.numeric(str_sub(avg_lon, start = 7L, end = -1L)),#str_sub:数値で指定して抽出
            avg_lat =as.numeric(str_sub(avg_lat, start = 1L, end = -2L)) ) %>%
  mutate (year_st  = substring_index(first_timestamp, "-",1),
            month_st  = substring_index(substring_index(first_timestamp, "-",2), "-", -1),
          day_st =  str_sub(substring_index(first_timestamp, "-",3), start =9, end = 10)) %>%
   mutate(ave_lon_R = round(avg_lon, temp_round_0),　　　# 緯度経度　round
           ave_lat_R = round(avg_lat, temp_round_0),
          ave_lon_R_1 = round(avg_lon, temp_round_1),　　　# 緯度経度　round
           ave_lat_R_1 = round(avg_lat, temp_round_1),
          ave_lon_R_2 = round(avg_lon, temp_round_2),　　　# 緯度経度　round
           ave_lat_R_2 = round(avg_lat, temp_round_2)) %>% 
  collect()


```



#韓国のeezでフィルタリング
```{r}

russia_eez_japan_korea_2018 <- dat_area_segs_daily_WE_2018 %>%
  mutate(country_code = as.integer(floor(ssvid/1000000)))  %>%  　　# ssvidから国コード生成
  left_join(list_country_codes, by = c("country_code" = "code" )) %>%
  filter(country_code %in% "273") %>% 
  # dat_sonota_joined を first_timestamp で結合
  left_join(dat_sonota_joined, by = c("first_timestamp", "seg_id")) %>% 
  # territory1 が "Japan" の行のみフィルタ
  filter(eez_id == 8328 ) %>% 
  #select(seg_id, ssvid, first_timestamp, eez_id, reporting_name) %>% 
   mutate(avg_lon = substring_index(avg_lat_lon, " ", 1),#avg_lat_lonをavg_lon,avg_latに分ける
          avg_lat = substring_index(avg_lat_lon, " ", -1),
          seg_id_num  = as.numeric(str_sub(seg_id, start = 1L, end = -1L)))%>%
  mutate(avg_lon =as.numeric(str_sub(avg_lon, start = 7L, end = -1L)),#str_sub:数値で指定して抽出
            avg_lat =as.numeric(str_sub(avg_lat, start = 1L, end = -2L)) ) %>%
  mutate (year_st  = substring_index(first_timestamp, "-",1),
            month_st  = substring_index(substring_index(first_timestamp, "-",2), "-", -1),
          day_st =  str_sub(substring_index(first_timestamp, "-",3), start =9, end = 10)) %>%
   mutate(ave_lon_R = round(avg_lon, temp_round_0),　　　# 緯度経度　round
           ave_lat_R = round(avg_lat, temp_round_0),
          ave_lon_R_1 = round(avg_lon, temp_round_1),　　　# 緯度経度　round
           ave_lat_R_1 = round(avg_lat, temp_round_1),
          ave_lon_R_2 = round(avg_lon, temp_round_2),　　　# 緯度経度　round
           ave_lat_R_2 = round(avg_lat, temp_round_2)) %>% 
  collect() 
```


#spark終了不用意に走らせると面倒
```{r}
#spark_disconnect(sc = spark_conn)
```





```{r}
length(unique(russia_eez_japan_2018$ssvid))
```






#日本の排他的経済水域の排他的経済水域
```{r}




japan_sf <-rnaturalearth::ne_countries(country = c('japan','russia',
                                     'south korea',
                                     'north korea',
                                     'china','taiwan',
                                     'united states of america'),
                         scale="large",
                         returnclass = "sf") %>%　st_transform(crs=4326)
# EEZ
eez_sf <- MazamaSpatialUtils::SimpleCountriesEEZ |>
    st_as_sf() |>
    st_transform(crs = 4326) |>
    filter(countryName == "Japan") 

```



```{r}


# 日本と近隣国の国境データを取得
japan_sf <- rnaturalearth::ne_countries(country = c('Japan', 'Russia', 'South Korea', 
                                                     'North Korea', 'China', 'Taiwan', 
                                                     'United States of America'),
                                         scale = "large",
                                         returnclass = "sf") %>% 
  st_transform(crs = 4326)

# 日本のEEZデータを取得
eez_sf <- MazamaSpatialUtils::SimpleCountriesEEZ |>
    st_as_sf() |>
    st_transform(crs = 4326) |>
    filter(countryName == "Japan")

# ロシア船のEEZ内での操業データ (russia_eez_japan_2018)をフィルタ
# ここではrussia_eez_japan_2018が、緯度 (avg_lat) と経度 (avg_lon) を持っていると仮定
russia_vessel_sf <- russia_eez_japan_2018 %>%
  filter(!is.na(avg_lon) & !is.na(avg_lat)) %>%
  st_as_sf(coords = c("ave_lon_R_1", "ave_lat_R_2"), crs = 4326)

# プロットの作成
ggplot() +
  # 日本と近隣国の地図を描く
  geom_sf(data = japan_sf, fill = 'lightgray', color = 'black') +
  geom_sf(data = eez_sf, fill = 'blue', alpha = 0.3) +  # 日本のEEZを青で描く
  # ロシア船の操業データを緯度経度でプロット
  geom_sf(data = russia_vessel_sf, aes(color = "red"), size = 0.5) +  # ロシア船の位置を赤でプロット
  labs(title = "Russia Vessels Operating in Japan's EEZ") +
  theme_minimal() +
  theme(legend.position = "none")  # 凡例を非表示にする

```
```{r}
russia_vessel_sf <- russia_eez_japan_2018 %>%
  filter(!is.na(avg_lon) & !is.na(avg_lat)) %>%
  st_as_sf(coords = c("avg_lon", "avg_lat"), crs = 4326)

# プロットの作成
ggplot() +
  # 日本のEEZの地図を描く
  geom_sf(data = eez_sf, fill = 'blue', alpha = 0.3) +  # 日本のEEZを青で描く
  # ロシア船の操業データを緯度経度でプロット
  geom_sf(data = russia_vessel_sf, aes(color = "red"), size = 0.5) +  # ロシア船の位置を赤でプロット
  labs(title = "Russia Vessels Operating in Japan's EEZ") +
  theme_minimal() +
  theme(legend.position = "none") +  # 凡例を非表示にする
  coord_sf(xlim = c(122, 153), ylim = c(24, 45))  # 日本のEEZ範囲に絞る
```


```{r}
# 日本の陸地データを取得
land_sf <- rnaturalearth::ne_countries(country = 'Japan', scale = "large", returnclass = "sf") %>%
  st_transform(crs = 4326)

# ロシア船のEEZ内での操業データ (russia_eez_japan_2018)をフィルタ
# ここではrussia_eez_japan_2018が、緯度 (avg_lat) と経度 (avg_lon) を持っていると仮定
russia_vessel_sf <- russia_eez_japan_2018 %>%
  filter(!is.na(avg_lon) & !is.na(avg_lat)) %>%
  st_as_sf(coords = c("avg_lon", "avg_lat"), crs = 4326)

# プロットの作成
ggplot() +
  # 日本のEEZの地図を描く
  geom_sf(data = eez_sf, fill = 'blue', alpha = 0.3) +  # 日本のEEZを青で描く
  # 日本の陸地を描く
  geom_sf(data = land_sf, fill = 'lightgreen', color = 'black') +  # 日本の陸地を緑で描く
  # ロシア船の操業データを緯度経度でプロット
  geom_sf(data = russia_vessel_sf, aes(color = "red"), size = 0.5) +  # ロシア船の位置を赤でプロット
  labs(title = "Russia Vessels Operating in Japan's EEZ") +
  theme_minimal() +
  theme(legend.position = "none") +  # 凡例を非表示にする
  coord_sf(xlim = c(120, 160), ylim = c(15, 50))  # 日本のEEZ範囲に絞る
```
```{r}

# アジア全体の陸地データを取得
asia_sf <- rnaturalearth::ne_countries(continent = "Asia", scale = "large", returnclass = "sf") %>%
  st_transform(crs = 4326)

# ロシア船のEEZ内での操業データ (russia_eez_japan_2018)をフィルタ
# ここではrussia_eez_japan_2018が、緯度 (avg_lat) と経度 (avg_lon) を持っていると仮定
russia_vessel_sf <- russia_eez_japan_2018 %>%
  filter(!is.na(avg_lon) & !is.na(avg_lat)) %>%
  st_as_sf(coords = c("avg_lon", "avg_lat"), crs = 4326)

# プロットの作成
ggplot() +
  # アジアの陸地を描く
  geom_sf(data = asia_sf, fill = 'lightgray', color = 'black') +  # アジアの陸地を灰色で描く
  # 日本のEEZの地図を描く
  geom_sf(data = eez_sf, fill = 'blue', alpha = 0.3) +  # 日本のEEZを青で描く
  # 日本の陸地を描く
  geom_sf(data = land_sf, fill = 'lightgreen', color = 'black') +  # 日本の陸地を緑で描く
  # ロシア船の操業データを緯度経度でプロット
  geom_sf(data = russia_vessel_sf, aes(color = "red"), size = 0.5) +  # ロシア船の位置を赤でプロット
  labs(title = "Russia Vessels Operating in Japan's EEZ") +
  theme_minimal() +
  theme(legend.position = "none") +  # 凡例を非表示にする
  coord_sf(xlim = c(120, 160), ylim = c(20, 50))  # 日本のEEZ範囲に絞る
```



```{r}
# ロシアの陸地データを取得
russia_sf <- rnaturalearth::ne_countries(country = "Russia", scale = "large", returnclass = "sf") %>%
  st_transform(crs = 4326)

# ロシア船のEEZ内での操業データ (russia_eez_japan_2018)をフィルタ
# ここではrussia_eez_japan_2018が、緯度 (avg_lat) と経度 (avg_lon) を持っていると仮定
russia_vessel_sf <- russia_eez_japan_2018 %>%
  filter(!is.na(avg_lon) & !is.na(avg_lat)) %>%
  st_as_sf(coords = c("avg_lon", "avg_lat"), crs = 4326)

# プロットの作成
ggplot() +
  # アジアの陸地を描く
  geom_sf(data = asia_sf, fill = 'lightgray', color = 'black') +  # アジアの陸地を灰色で描く
  # ロシアの陸地を描く
  geom_sf(data = russia_sf, fill = 'lightpink', color = 'black') +  # ロシアの陸地を薄ピンクで描く
  # 日本のEEZの地図を描く
  geom_sf(data = eez_sf, fill = 'blue', alpha = 0.3) +  # 日本のEEZを青で描く
  # 日本の陸地を描く
  geom_sf(data = land_sf, fill = 'lightgreen', color = 'black') +  # 日本の陸地を緑で描く
  # ロシア船の操業データを緯度経度でプロット
  geom_sf(data = russia_vessel_sf, aes(color = "red"), size = 0.5) +  # ロシア船の位置を赤でプロット
  labs(title = "Russia Vessels Operating in Japan's EEZ") +
  theme_minimal() +
  theme(legend.position = "none") +  # 凡例を非表示にする
  coord_sf(xlim = c(120, 160), ylim = c(20, 50))  # 日本のEEZ範囲に絞る
```

#segsデータの読み込み
```{r}
russia_eez_seg_csv <- read.csv("/Users/oyamakei/Desktop/Gakulabwork/big_area_segs_russia.csv")
```

```{r}

length(unique(russia_eez_japan_2018$ssvid))
length(unique(russia_eez_seg_csv$ssvid))

# 共通する値の数を算出
common_ssvid_count <- intersect(russia_eez_japan_2018$ssvid, russia_eez_seg_csv$ssvid) %>%
  length()

# 結果を出力
print(common_ssvid_count)
```



```{r}
  russia_eez_segs <- russia_eez_seg_csv %>%
   mutate(
    avg_lat = str_extract(avg_lat_lon, "(?<=POINT\\().*?(?= )") %>% as.numeric(),
    avg_lon = str_extract(avg_lat_lon, "(?<= ).*?(?=\\))") %>% as.numeric()
  )


str(russia_eez_seg_csv$avg_lat_lon)
  
```



```{r}
russia_vessel_sf_segs <- russia_eez_segs %>%
  filter(!is.na(avg_lon) & !is.na(avg_lat)) %>%
  st_as_sf(coords = c("avg_lon", "avg_lat"), crs = 4326)

# プロットの作成
ggplot() +
  # アジアの陸地を描く
  geom_sf(data = asia_sf, fill = 'lightgray', color = 'black') +  # アジアの陸地を灰色で描く
  # ロシアの陸地を描く
  geom_sf(data = russia_sf, fill = 'lightpink', color = 'black') +  # ロシアの陸地を薄ピンクで描く
  # 日本のEEZの地図を描く
  geom_sf(data = eez_sf, fill = 'blue', alpha = 0.3) +  # 日本のEEZを青で描く
  # 日本の陸地を描く
  geom_sf(data = land_sf, fill = 'lightgreen', color = 'black') +  # 日本の陸地を緑で描く
  # ロシア船の操業データを緯度経度でプロット
  geom_sf(data = russia_vessel_sf, aes(color = "red"), size = 0.5) +  # ロシア船の位置を赤でプロット
  labs(title = "Russia Vessels Operating in Japan's EEZ") +
  theme_minimal() +
  theme(legend.position = "none") +  # 凡例を非表示にする
  coord_sf(xlim = c(120, 160), ylim = c(20, 50))  # 日本のEEZ範囲に絞る
```




#韓国と日本のeez両方で操業しているロシア船の数365隻だった
```{r}
# 共通する ssvid を取得
common_ssvid <- intersect(russia_eez_japan_2018$ssvid, russia_eez_japan_korea_2018$ssvid)

# 共通する ssvid の数を取得
common_count <- length(common_ssvid)

# 結果を出力
print(common_count)
```
#試しに273390570のsegsでの動向
```{r}

is_present <- russia_eez_segs %>% 
  filter(ssvid == 273390570) %>% 
  nrow() > 0 

print(is_present)




check_273390570 <-  russia_eez_segs %>% 
  filter(ssvid == 273390570)

check_273390570_sf <- st_as_sf(
  check_273390570,
  coords = c("avg_lat", "avg_lon"),   # 緯度と経度を指定
  crs = 4326                 # 座標系を指定 (例: WGS84)
)

ggplot() +
  # アジアの陸地を描く
  geom_sf(data = asia_sf, fill = 'lightgray', color = 'black') +  # アジアの陸地を灰色で描く
  # ロシアの陸地を描く
  geom_sf(data = russia_sf, fill = 'lightpink', color = 'black') +  # ロシアの陸地を薄ピンクで描く
  # 日本のEEZの地図を描く
  geom_sf(data = eez_sf, fill = 'blue', alpha = 0.3) +  # 日本のEEZを青で描く
  # 日本の陸地を描く
  geom_sf(data = land_sf, fill = 'lightgreen', color = 'black') +  # 日本の陸地を緑で描く
  # ロシア船の操業データを緯度経度でプロット
  geom_sf(data = check_273390570_sf, aes(color = "red"), size = 0.5) +  # ロシア船の位置を赤でプロット
  labs(title = "check_273390570") +
  theme_minimal() +
  theme(legend.position = "none") +  # 凡例を非表示にする
  coord_sf(xlim = c(120, 160), ylim = c(20, 50))  # 日本のEEZ範囲に絞る

```








































